{% set name = "pybind11-stubgen" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybind11-stubgen-{{ version }}.tar.gz
  sha256: 0ed70a8bef38cb45c90f4884631923be9000de1f636d3265ca2079186cd750ce

build:
  number: 0
  noarch: python
  entry_points:
    - pybind11-stubgen = pybind11_stubgen.__init__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - pybind11_stubgen
  commands:
    - pip check
    - pybind11-stubgen --help
  requires:
    - pip

about:
  home: https://github.com/sizmailov/pybind11-stubgen
  summary: PEP 561 type stubs generator for pybind11 modules
  license: BSD-Protection
  license_file: LICENSE

extra:
  recipe-maintainers:
    - allanleal
